<a href="https://colab.research.google.com/github/ktaran-jeet/3dVision/blob/DLNotes/Linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
##Linear module:
import torch
import torch.nn as nn

In [3]:
#In the context of neural networks, a linear layer (also known as a fully connected layer or dense layer) applies a linear transformation to its input. This transformation is defined by the equation: y = x * W^T + b
module = nn.Linear(5,3)
print(module)

Linear(in_features=5, out_features=3, bias=True)


In [4]:
ip = torch.rand(5)
print(ip)

tensor([0.5478, 0.0385, 0.7758, 0.4499, 0.9995])


In [5]:
y = module(ip)
print(y)

tensor([-0.3043, -0.3537, -0.3266], grad_fn=<ViewBackward0>)


In [6]:
print(module.weight)
print(module.weight.size())

Parameter containing:
tensor([[-0.0118,  0.3327, -0.2300, -0.3586, -0.0776],
        [ 0.0556,  0.0843, -0.2661, -0.2053, -0.1646],
        [-0.3621, -0.2757,  0.0608,  0.0439, -0.3471]], requires_grad=True)
torch.Size([3, 5])


In [7]:
print(module.bias)
print(module.bias.size())

Parameter containing:
tensor([0.1067, 0.0759, 0.1624], requires_grad=True)
torch.Size([3])


In [9]:
##The primary purpose of using with torch.no_grad(): is to temporarily disable gradient calculations within the code block it encloses.
## during inference, evaluation or durring manipulating model params directly.
with torch.no_grad():
  module.weight[0,0] = 0
  module.weight[2,0] = 0
  module.bias[0] = 0
  print(module.weight)
  print(module.bias)

Parameter containing:
tensor([[ 0.0000,  0.3327, -0.2300, -0.3586, -0.0776],
        [ 0.0556,  0.0843, -0.2661, -0.2053, -0.1646],
        [ 0.0000, -0.2757,  0.0608,  0.0439, -0.3471]], requires_grad=True)
Parameter containing:
tensor([0.0000, 0.0759, 0.1624], requires_grad=True)


In [10]:
## A linear module without bias:
mod = nn.Linear(5,3,bias=False)
print(mod)

Linear(in_features=5, out_features=3, bias=False)


In [11]:
print(mod.weight)
print(mod.bias)

Parameter containing:
tensor([[-0.2350,  0.3146,  0.1782,  0.2786, -0.3635],
        [-0.2029, -0.1665, -0.1583, -0.2693,  0.3832],
        [-0.1886,  0.2933,  0.1280, -0.0670, -0.0914]], requires_grad=True)
None
