<a href="https://colab.research.google.com/github/ktaran-jeet/3dVision/blob/DLNotes/PytorchRevision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
### A journey of thousand miles begins with a single step!
### Let's dive into deep learning basics, every concept from scratch:

In [4]:
## 1.Tensors
import torch
print(torch.__version__)

2.5.0+cu121


In [20]:
x = torch.tensor([[1,7,6],[4,1,2],[21,30,1]])
x[2,0] = 42
x
x[-1,-1]

tensor(1)

In [18]:
torch.zeros(3,4,2)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])

In [27]:
torch.ones(2,2)*4 + torch.ones(2,2) - torch.ones(2,2)

tensor([[4., 4.],
        [4., 4.]])

In [33]:
a = torch.ones(2,1)
b = torch.ones(2,1)
print(a)
print(b)
a+b

tensor([[1.],
        [1.]])
tensor([[1.],
        [1.]])


tensor([[2.],
        [2.]])

In [45]:
## returns a random number from a uniform distribution between [0,1], output tensor is of size specified.
c = torch.rand(4)
d = torch.rand(3,4)
print(c)
print(d)

tensor([0.8815, 0.8912, 0.4836, 0.8303])
tensor([[0.8607, 0.4509, 0.2435, 0.1983],
        [0.3228, 0.2344, 0.0469, 0.8031],
        [0.3709, 0.5479, 0.6521, 0.2630]])


In [53]:
## .item() takes no argument and works on scalar and pulls out a python value, tensor of rank 0.
q = torch.rand(1)
print(q)
p =q.item()
print(p)
print(type(p))

tensor([0.4348])
0.4347659945487976
<class 'float'>


In [50]:
print(q.device)
print(q.type)

cpu
<built-in method type of Tensor object at 0x7a843d8c6ed0>


In [78]:
## max() returns the maximum value in the tensor:
## arr.max() or tensor.max(arr) ...
arr = torch.rand(3,4)
print(arr)
m = arr.max()
print(m)
print(arr.max().item())

tensor([[0.5746, 0.3610, 0.3693, 0.8721],
        [0.5202, 0.9277, 0.1568, 0.2712],
        [0.4933, 0.0907, 0.8101, 0.3391]])
tensor(0.9277)
0.9276611804962158


In [77]:
#If a dimension is specified, it returns both the maximum values and their corresponding indices.
## dim ranges depends on the dimensions of the tensor.
#for tensor below, there are 2 dimesions only:
#dim=0: Finds the maximum values along dimension 0 i.e you get a row as output, means comparing elements column wise
#dim=1: Finds the maximum values along dimension 1 i.e you get a column as output, means comparing elements row wise
#dim=-1 -> last dimension which is dim=1 and so on.
x = torch.tensor([[11, 3, 5], [7, 2, 48]])
print(x)
max_values, max_indices = torch.max(x, dim=0)
print("Max values:", max_values)
print("Max indices:", max_indices)
print("overall max", x.max())

tensor([[11,  3,  5],
        [ 7,  2, 48]])
Max values: tensor([11,  3, 48])
Max indices: tensor([0, 0, 1])
overall max tensor(48)


In [72]:
# argmax() returns only the indices of the maximum values along a specified dimension.
z = torch.tensor([[11, 3, 5], [7, 2, 48]])
print(z)
indices = torch.argmax(z, dim=1)
print(indices)
print(z.argmax(dim=0))

tensor([[11,  3,  5],
        [ 7,  2, 48]])
tensor([0, 2])
tensor([0, 0, 1])


In [84]:
#Datatypes of tensors:
long_tens = torch.tensor([[11, 3, 5], [7, 2, 48]], dtype=torch.long)
print(long_tens)
print(long_tens.dtype)
## change type of tensor:
float_tens = long_tens.type(torch.float32)
print(float_tens)
print(float_tens.dtype)
##using function .to()
xxy = torch.tensor([[11, 3, 5], [7, 2, 48]]).to(dtype=torch.long)
print(xxy.dtype)

tensor([[11,  3,  5],
        [ 7,  2, 48]])
torch.int64
tensor([[11.,  3.,  5.],
        [ 7.,  2., 48.]])
torch.float32
torch.int64


In [85]:
## Most of the tensor operations that return a tensor create a new tensor. If you want to save memory and perform in-place opn then use the same fn name with appended _ like:
ran_tens = torch.rand(2,2)
z = ran_tens.log2()
print(z)
print(ran_tens)
ran_tens.log2_()
print(ran_tens)

tensor([[-0.8229, -0.6146],
        [-1.1174, -0.4164]])
tensor([[0.5653, 0.6531],
        [0.4609, 0.7493]])
tensor([[-0.8229, -0.6146],
        [-1.1174, -0.4164]])


In [89]:
## view() and reshape() both can be used to reshape the tensors to the desired shape: the no. of elements before and after must be same.
##view() can throw errors if the required view is not contiguous;you have to call tensor.contiguous() before. In general, it's better to use reshape() as it does all of this behind the scenes.
nmist = torch.rand(784)
v = nmist.view(1,28,28)
print(v.shape)
rt = torch.reshape(nmist,(1,28,28))
print(rt.shape)

torch.Size([1, 28, 28])
torch.Size([1, 28, 28])


In [91]:
## permute(): To change the order of input eg. from h,w,channels to c,h,w
hwc = torch.rand(640,480,3)
chw = hwc.permute(2,0,1)
print(chw.shape)

torch.Size([3, 640, 480])


In [92]:
##Tensor broadcasting::Tensor broadcasting is a powerful mechanism in PyTorch and NumPy that allows you to perform element-wise operations on tensors with different shapes, as long as their dimensions are compatible.This is done without explicitly creating copies of the data, making it memory-efficient.
#Rules for Broadcasting: Two dimensions are compatible if:
#They are equal, or One of them is 1.
a = torch.tensor([1,2,3])  #shape = (3,)
b = torch.tensor([[4,5,6],[7,8,9]]) #shape = (2,3)
#string from trailing dims, both has 3(equal) Since a has only one dimension, it is broadcasted along the first dimension to match the shape of b
print(a)
print(b)
print(a+b)

tensor([1, 2, 3])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[ 5,  7,  9],
        [ 8, 10, 12]])


In [99]:
x = torch.tensor([1,2,3]) ## [1,2,3] is expanded to match y , [[1,2,3]]
y = torch.tensor([[4]])
print(x.shape)
print(y.shape)
print(x+y)
print((x+y).shape)

torch.Size([3])
torch.Size([1, 1])
tensor([[5, 6, 7]])
torch.Size([1, 3])


In [100]:
x = torch.tensor([1,2,3]) ## [1,2,3] is expanded to match y , [[1,2,3], [1,2,3]] --> singleton dimension.
y = torch.tensor([[4], [6]])
print(x.shape)
print(y.shape)
print(x+y)
print((x+y).shape)

torch.Size([3])
torch.Size([2, 1])
tensor([[5, 6, 7],
        [7, 8, 9]])
torch.Size([2, 3])


In [107]:
x = torch.tensor([1,2,3])
y = torch.tensor([[4]])
z = torch.tensor([[4],[11],[0]])
print(x.shape)
print(y.shape)
print(z.shape)
print("-----------------")
print(x+y)
print((x+y).shape)
print(x+y+z)
print((x+y+z).shape)

torch.Size([3])
torch.Size([1, 1])
torch.Size([3, 1])
-----------------
tensor([[5, 6, 7]])
torch.Size([1, 3])
tensor([[ 9, 10, 11],
        [16, 17, 18],
        [ 5,  6,  7]])
torch.Size([3, 3])
