<a href="https://colab.research.google.com/github/ktaran-jeet/3dVision/blob/DLNotes/PytorchRevision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
### A journey of thousand miles begins with a single step!
### Let's dive into deep learning basics, every concept from scratch:

In [4]:
## 1.Tensors
import torch
print(torch.__version__)

2.5.0+cu121


In [20]:
x = torch.tensor([[1,7,6],[4,1,2],[21,30,1]])
x[2,0] = 42
x
x[-1,-1]

tensor(1)

In [18]:
torch.zeros(3,4,2)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])

In [27]:
torch.ones(2,2)*4 + torch.ones(2,2) - torch.ones(2,2)

tensor([[4., 4.],
        [4., 4.]])

In [33]:
a = torch.ones(2,1)
b = torch.ones(2,1)
print(a)
print(b)
a+b

tensor([[1.],
        [1.]])
tensor([[1.],
        [1.]])


tensor([[2.],
        [2.]])

In [45]:
## returns a random number from a uniform distribution between [0,1], output tensor is of size specified.
c = torch.rand(4)
d = torch.rand(3,4)
print(c)
print(d)

tensor([0.8815, 0.8912, 0.4836, 0.8303])
tensor([[0.8607, 0.4509, 0.2435, 0.1983],
        [0.3228, 0.2344, 0.0469, 0.8031],
        [0.3709, 0.5479, 0.6521, 0.2630]])


In [53]:
## .item() takes no argument and works on scalar and pulls out a python value, tensor of rank 0.
q = torch.rand(1)
print(q)
p =q.item()
print(p)
print(type(p))

tensor([0.4348])
0.4347659945487976
<class 'float'>


In [50]:
print(q.device)
print(q.type)

cpu
<built-in method type of Tensor object at 0x7a843d8c6ed0>


In [59]:
arr = torch.rand(3,4)
print(arr)
m = arr.max()
print(m)
print(arr.max().item())
indices = arr.argmax()
print(indices)

tensor([[0.9511, 0.6751, 0.4007, 0.5760],
        [0.0142, 0.5410, 0.0067, 0.9421],
        [0.7706, 0.1981, 0.0411, 0.6398]])
tensor(0.9511)
0.9511238932609558
tensor(0)


In [77]:
#If a dimension is specified, it returns both the maximum values and their corresponding indices.
## dim ranges depends on the dimensions of the tensor.
#for tensor below, there are 2 dimesions only:
#dim=0: Finds the maximum values along dimension 0 i.e you get a row as output, means comparing elements column wise
#dim=1: Finds the maximum values along dimension 1 i.e you get a column as output, means comparing elements row wise
#dim=-1 -> last dimension which is dim=1 and so on.
x = torch.tensor([[11, 3, 5], [7, 2, 48]])
print(x)
max_values, max_indices = torch.max(x, dim=0)
print("Max values:", max_values)
print("Max indices:", max_indices)
print("overall max", x.max())

tensor([[11,  3,  5],
        [ 7,  2, 48]])
Max values: tensor([11,  3, 48])
Max indices: tensor([0, 0, 1])
overall max tensor(48)


In [72]:
# argmax() returns only the indices of the maximum values along a specified dimension.
z = torch.tensor([[11, 3, 5], [7, 2, 48]])
print(z)
indices = torch.argmax(z, dim=1)
print(indices)
print(z.argmax(dim=0))

tensor([[11,  3,  5],
        [ 7,  2, 48]])
tensor([0, 2])
tensor([0, 0, 1])


In [ ]:
#Datatypes of tensors:
